## 서버 포트 설정
server:
  port: 8723
  
## 오라클 드라이버 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    view-names:
    - thymeleaf/*
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: C##NNDI
    password: NNDI
    hikari:
      auto-commit: false
      
  jpa:
    generate-ddl: false
    show-sql: true 
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true  
        
        